// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'pref-api-token'
  | 'pref-api-token-help'
  | 'pref-api-url'
  | 'pref-api-url-help'
  | 'pref-auto-import'
  | 'pref-auto-import-help'
  | 'pref-eagle-folder'
  | 'pref-eagle-folder-help'
  | 'pref-help'
  | 'pref-test-connection'
  | 'pref-title'
  | 'prefs-title'
  | 'status-auto-disabled'
  | 'status-auto-enabled'
  | 'status-connection-failed'
  | 'status-connection-success'
  | 'status-export-empty'
  | 'status-export-failed'
  | 'status-export-partial'
  | 'status-export-success';
