// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableAutoImport": boolean;
      "eagleApiUrl": string;
      "eagleApiToken": string;
      "eagleFolderId": string;
      "thumbnailSize": number;
      "noteThumbnailSize": number;
      "showFileSize": boolean;
      "showModifiedTime": boolean;
      "defaultSortField": string;
      "defaultSortOrder": string;
      "noteDoubleClickOpenMode": string;
      "excludeFolders": string;
      "confirmDelete": boolean;
      "imageManagerTrash": string;
      "noteImageManagerTrash": string;
    };
  }
}
